import { Header } from '@/components/layout/Header'
import './globals.css'
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs'
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  
  const supabase = createServerComponentClient({ cookies })

  
  const {
    data: { user },
  } = await supabase.auth.getUser()


  return (
    <html lang="en">
      <body>
        <main className="min-h-screen bg-background flex flex-col items-center">
          <Header user={user} />
          {children}
        </main>
      </body>
    </html>
  )
}
