import { Sidebar } from '@/components/layout/Sidebar';
import { Database } from '@/types';
import { createServerComponentClient } from '@supabase/auth-helpers-nextjs';
import { cookies } from 'next/headers';
import { redirect } from 'next/navigation';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient<Database>({ cookies });

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) redirect('/');

  const { data: staffUserData, error } = await supabase
    .from('staff_users')
    .select('*')
    .eq('user_id', user.id)
    .limit(1)
    .single();
  if (error || !staffUserData) redirect('/');

  if (
    staffUserData.staff_role === 'ADMIN' ||
    staffUserData.staff_role === 'MANAGER'
  ) {
    return (
      <main className='h-fill flex w-full grow flex-row bg-background'>
        <Sidebar staffRole={staffUserData.staff_role} />
        <div className='flex w-full flex-col items-center justify-center'>
          {children}
        </div>
      </main>
    );
  } else {
    redirect('/');
  }
}
