import { Sidebar } from "@/components/layout/Sidebar";
import { Database } from "@/types";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  
  const supabase = createServerComponentClient<Database>({ cookies })
  
  const { data: { user } } = await supabase.auth.getUser()

  if (!user) redirect('/')

  const { data: userData, error } = await supabase
    .from('discord_users')
    .select('staff_role')
    .eq('user_id', user.id)
    .limit(1)
        .single()
    
  
  if (error || !userData) redirect('/')
  
  if (userData.staff_role !== 'ADMIN') redirect('/')

  return (
    <main className="bg-background grow flex flex-row w-full h-fill">
      <Sidebar />
      <div className="w-full flex flex-col ">
        {children}
      </div>  
    </main>
  );
}
